### PR TITLE
Post tree map improvement

### PR DESCRIPTION
**Pull request by nwoetzel**
This is my attempt to fix the problem in hierarchical posts.
The previous siblings map (which is still used for terms) makes things a little harder to wrap ones head around. The basic idea of this proposed implementation is, that for each post, all ancestors (parents, parents of parents ...) are stored .
It would be nicer and more efficient, if this would be done on the database. The keyword is https://en.wikipedia.org/wiki/Transitive_closure
But wordpress does not have an api for that ancestor map of a post (or term). And each database provider has a slightly different way to implement that. So this might just be an unreachable goal.

Now if we want to test, if a user has access to that post, we need to check if there is no restriction on the parents, or if the user has explicit rights for any of the parents - either will grant access (or inverse will add them to excluded posts).

### CODE REVIEW

**Comment by GM-Alex** [comment]
With out testing and only a short look (I only read the PR description and had a short look at the source code) I would say that the current getPostTreeMap function has the same result as your implementation. It collects all child posts for a post, like:

`
[parentOneId] => [childOneId, childTwoId, ...]
[parentTwoId] => [childOneId, childTwoId, ...]
`

But the current implementation is much shorter and requires only one database request. Yes there is some potential to optimize the sibling resolving by ordering them, which I will do during the refactoring, but that shouldn't effect the performance much. 

So I don't think to merge that. Or do I miss understand something. The only way to have a good tree handling in mysql are nested sets, because mysql aren't supporting recursion in the way you need it like oracle does. Maybe stored procedures could do the trick, I'm not sure, but they need to much right on the database.

**Comment by nwoetzel** [comment]
My explanation was probably not good enough, but what your code collects are descendants, while the proposed code collects ancestors:
`[childId] => [parentId, grandFatherId, greatGrandFatherId, ...]` which makes it easier to check for a post if it is locked through one of the ancestors.

**Comment by GM-Alex** [comment]
Ah ok I got it you are calculating the path for the post. I will have a closer look at it, this week.

**Comment by GM-Alex** [comment]
Is now obsolete.

**Pull request closed without merging**
