### PR TITLE
setAtAdminPanel was called too late using the amin_init filter

### PR DESCRIPTION
**Pull request by nwoetzel**
-wordpress might have changed something in the order filter and actions are called? Or someting somewhere in the code has changed in the order things are executed
-the admin_init action is called too late, so that setAtAdminPanel is not set to true and the call to $oUserAccessManager->noRightsToEditContent() does not work properly since it relies on that
-replaced that logic by implementing 'atAdminPanel' using worpdress' is_admin() function https://codex.wordpress.org/Function_Reference/is_admin

### CODE REVIEW

**Comment by nwoetzel** [comment]
I think this is a real bug, that needs fixing soon.

**Comment by GM-Alex** [comment]
I already fixed that at the next branch. I will see how the work is going on, maybe I will make a small release with that fix.

**Comment by nwoetzel** [comment]
Thanks. Correct me if I am wrong, but you are not planning on "supporting" the current master with new releases anymore, but you want to do you rework in the 'next' branch and merge it into master? Make a release and then pull-requests are more welcome?
I will than just collect the changes in my fork and patch my installation with it. And I will not bother you with things I consider fixes until you get into a new release cycle?

**Comment by GM-Alex** [comment]
Is now obsolete.

**Pull request closed without merging**
